package data;

import utils.Utils;

import java.util.*;

/**
 * A Class used for generating number sequences based on supplied patterns and number lists.
 */
public class GenerateNumberSequences
{
    private Set<String> sequences;

    // ==========================================================================================
    // Markov Methods
    // ==========================================================================================

    /**
     * First checks if the generated markov number list will satisfy the markov pattens. {@link #doesSetSatisfyPatterns(MarkovAlg)}
     * Then proceeds to generate all possible number combinations with the provided number list and stored only those which satisfy all 3 patterns.
     *
     * @param markov
     */
    public void generateNextSequenceViaMarkov(MarkovAlg markov)
    {
        if (doesSetSatisfyPatterns(markov))
            System.out.println("Number Set satisfies all 3 color, high/low and odd/even patterns.");
        else return;

        sequences = generateAllNumberSequencesForNumberList(
                Utils.generateColorPatternTemplateForNumberList(markov.getNextBestNumbers()), new LinkedHashSet<>(),
                Utils.convertStringToIntegerArray(markov.getNextColorPattern()), markov.getNextHighLowPattern(), markov.getNextOddEvenPattern(),
                new int[6], 0);
    }

    /**
     * NOTE: The number list and all 3 top patterns are generated by the markov algorithm.
     * This method checks if there are enough number variance in the list to satisfy each pattern when generating the number sequences.
     *
     * @param markov
     * @return True - if all 3 patterns were satisfied, False - when at least 1 wasn't
     */
    private boolean doesSetSatisfyPatterns(MarkovAlg markov)
    {
        if (!Utils.doesNumberSetSatisfyColorPattern(markov.getNextBestNumbers(), markov.getNextColorPattern()))
        {
            System.out.println("Number Set doesn't satisfy the next color pattern.");
            return false;
        }
        if (!Utils.doesNumberSetSatisfyHighLowPattern(markov.getNextBestNumbers(), markov.getNextHighLowPattern()))
        {
            System.out.println("Number Set doesn't satisfy the next high/low pattern.");
            return false;
        }
        if (!Utils.doesNumberSetSatisfyOddEvenPattern(markov.getNextBestNumbers(), markov.getNextOddEvenPattern()))
        {
            System.out.println("Number Set doesn't satisfy the next odd/even pattern.");
            return false;
        }
        return true;
    }

    // ==========================================================================================
    // All Combinations Methods
    // ==========================================================================================

    /**
     * Generates either all number sequences for the best pattern of each group or a random one and then mutates it 49 times.
     * NOTE: The mutation algorithm is taken from the LottoMetrix website.
     *
     * @param colorPattern    The color pattern number sequences should generated against
     * @param highLowPattern  The high/low pattern number sequences should generated against
     * @param oddEvenPattern  The odd/even pattern number sequences should generated against
     * @param allCombinations True - generate all possible combinations for the patterns, False - generate a random sequence and then mutate it
     */
    public void generateAllNumberSequencesForPatterns(String colorPattern, String highLowPattern, String oddEvenPattern, boolean allCombinations)
    {
        sequences = allCombinations
                ? generateAllNumberSequencesForNumberList(
                Utils.generateCompleteColorPatternTemplate(), new LinkedHashSet<>(),
                Utils.convertStringToIntegerArray(colorPattern), highLowPattern, oddEvenPattern, new int[6], 0)
                : generateNumberSequencesViaMutation(colorPattern, highLowPattern, oddEvenPattern);
    }

    /**
     * Generates every single possible number combination for the provided patterns, RECURSIVELY.
     * NOTE: it stores them in a LinkedHashSet so there will be no duplicate entries and the map will be sorted.
     * Also before adding then to the set every sequence is checked if it satisfies a odd/even and high/low rule and it is sorted as well.
     *
     * @param template       The color pattern template, a list representation of a color pattern filled with number which will be used when generating the sequences
     * @param results        The set that will contain all combinations, HashSet(not sorted) or LinkedHashSet(sorted)
     * @param colorPattern   The color pattern that number sequences should generated against
     * @param highLowPattern The high/low pattern that number sequences should generated against
     * @param oddEvenPattern The odd/even pattern that number sequences should generated against
     * @param sequence       Temp array for storing generated sequences, should be null when the method is called, MUST be an empty array
     * @param seqIndex       The current array index where a number is being added, MUST be 0 at start
     * @return Set of generated number sequences as String
     */
    private Set<String> generateAllNumberSequencesForNumberList(Map<Integer, List<Integer>> template, Set<String> results, int[] colorPattern, String highLowPattern, String oddEvenPattern, int[] sequence, int seqIndex)
    {
        if (seqIndex == 6)
        {
            if (Utils.doesNumberSequenceSatisfyHighLowPattern(sequence, highLowPattern)
                    && Utils.doesNumberSequenceSatisfyOddEvenPattern(sequence, oddEvenPattern))
            {
                int[] clone = sequence.clone();
                Arrays.sort(clone);
                results.add(Utils.convertIntegerArrayToString(clone));
            }
        } else
        {
            for (int num : template.get(colorPattern[seqIndex]))
            {
                if (Utils.doesIntegerArrayContains(sequence, num)) continue;
                sequence[seqIndex] = num;
                generateAllNumberSequencesForNumberList(template, results, colorPattern, highLowPattern, oddEvenPattern, sequence, seqIndex + 1);
            }
        }
        return results;
    }

    // ==========================================================================================
    // Mutation Methods
    // ==========================================================================================

    /**
     * Generates number sequences starting by creating a random sequence by using the best color pattern.
     * Then it mutates that sequence 49 times (6/49) to get alternate number combinations which are then checked
     * if they satisfy the chosen color pattern and odd/even and high/low rule.
     * All sequences are stored in a LinkedHashSet as Strings so there are sorted and no duplicate ones can occur.
     *
     * @param colorPattern   The color pattern number sequences should generated against
     * @param highLowPattern The high/low pattern number sequences should generated against
     * @param oddEvenPattern The odd/even pattern number sequences should generated against
     */
    private Set<String> generateNumberSequencesViaMutation(String colorPattern, String highLowPattern, String oddEvenPattern)
    {
        // add the generation 0 number sequence
        LinkedHashSet<String> numSequences = new LinkedHashSet<>();
        int[] nextArr = generateRandomNumberSequenceForColorPattern(Utils.convertStringToIntegerArray(colorPattern));
        Arrays.sort(nextArr);
        numSequences.add(Utils.convertIntegerArrayToString(nextArr));
        int cnt = 49;
        while (--cnt > 0)
        {
            nextArr = mutateIntArray(nextArr);
            Arrays.sort(nextArr);
            if (Utils.doesNumberSequenceSatisfyColorPattern(nextArr, Utils.convertStringToIntegerArray(colorPattern))
                    && Utils.doesNumberSequenceSatisfyHighLowPattern(nextArr, highLowPattern)
                    && Utils.doesNumberSequenceSatisfyOddEvenPattern(nextArr, oddEvenPattern))
                numSequences.add(Utils.convertIntegerArrayToString(nextArr));
        }
        return numSequences;
    }

    /**
     * Generates a random 6 number sequence according to the provided pattern using a color sequence template table.
     * See ColorPatterns static method for more info.
     *
     * @param pattern The color pattern number sequences should generated against
     * @return The newly generated sequence as integer array
     */
    private int[] generateRandomNumberSequenceForColorPattern(int[] pattern)
    {
        int[] numSeq = new int[6];
        Random r = new Random();
        for (int i = 0; i < numSeq.length; i++)
        {
            int num = Utils.generateCompleteColorPatternTemplate().get(pattern[i])
                    .get(r.nextInt(Utils.generateCompleteColorPatternTemplate().get(pattern[i]).size()));
            // the pattern might have two consecutive color ids so we don't want to pick duplicate numbers, eg. 0, 1, 1, 2, 3, 4
            while (Utils.doesIntegerArrayContains(numSeq, num))
                num = Utils.generateCompleteColorPatternTemplate().get(pattern[i])
                        .get(r.nextInt(Utils.generateCompleteColorPatternTemplate().get(pattern[i]).size()));
            numSeq[i] = num;
        }
        return numSeq;
    }

    /**
     * Generates a next generation number sequence from the provided one as a int array.
     * The mutation happen by incrementing each number by 1. If the exceeds 49 it is set to 1 instead.
     *
     * @param arr The un-mutated original int array
     * @return The next mutated int array
     */
    private int[] mutateIntArray(int[] arr)
    {
        int[] mutatedArray = arr.clone();
        for (int i = 0; i < mutatedArray.length; i++)
        {
            if (mutatedArray[i] + 1 > 49)
            {
                mutatedArray[i] = 1;
                continue;
            }
            mutatedArray[i]++;
        }
        return mutatedArray;
    }

    // ==========================================================================================
    // Getter & Setter Methods
    // ==========================================================================================

    public Set<String> getSequences()
    {
        return sequences;
    }

}
